server:
  port: 7002

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb+srv://mendisdumindu21:spendWise@cluster0.zf3phab.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: savory-orders


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
